<?xml version="1.0" encoding="EUC-KR"?>
<!DOCTYPE root [
        <!ELEMENT root (subDeptList|_COLUMNS_OF_TABLE_TO_TEXT_)*>
        <!ATTLIST root
                xmlns CDATA #REQUIRED>
        <!ELEMENT subDeptList (list)*>
        <!ELEMENT list (prt_ord|dept|dept_code_nm|dept_nm|up_nm|up_dept|dept_div|colg|colg_nm)*>
        <!ELEMENT prt_ord (#PCDATA)>
        <!ELEMENT dept (#PCDATA)>
        <!ELEMENT dept_code_nm (#PCDATA)>
        <!ELEMENT dept_nm (#PCDATA)>
        <!ELEMENT up_nm (#PCDATA)>
        <!ELEMENT up_dept (#PCDATA)>
        <!ELEMENT dept_div (#PCDATA)>
        <!ELEMENT colg (#PCDATA)>
        <!ELEMENT colg_nm (#PCDATA)>
        <!ELEMENT _COLUMNS_OF_TABLE_TO_TEXT_ (#PCDATA)>
        ]>
<root xmlns="">
    <subDeptList>
        <list>
            <prt_ord>
                <![CDATA[21100]]>
            </prt_ord>
            <dept>
                <![CDATA[A201140214]]>
            </dept>
            <dept_code_nm>
                <![CDATA[A201140214-행정학과]]>
            </dept_code_nm>
            <dept_nm>
                <![CDATA[행정학과]]>
            </dept_nm>
            <up_nm>
                <![CDATA[정경대학]]>
            </up_nm>
            <up_dept>
                <![CDATA[A201120212]]>
            </up_dept>
            <dept_div>
                <![CDATA[210]]>
            </dept_div>
            <colg>
                <![CDATA[20112]]>
            </colg>
            <colg_nm>
                <![CDATA[정경대학]]>
            </colg_nm>
        </list>
        <list>
            <prt_ord>
                <![CDATA[21200]]>
            </prt_ord>
            <dept>
                <![CDATA[A201150215]]>
            </dept>
            <dept_code_nm>
                <![CDATA[A201150215-국제관계학과]]>
            </dept_code_nm>
            <dept_nm>
                <![CDATA[국제관계학과]]>
            </dept_nm>
            <up_nm>
                <![CDATA[정경대학]]>
            </up_nm>
            <up_dept>
                <![CDATA[A201120212]]>
            </up_dept>
            <dept_div>
                <![CDATA[210]]>
            </dept_div>
            <colg>
                <![CDATA[20112]]>
            </colg>
            <colg_nm>
                <![CDATA[정경대학]]>
            </colg_nm>
        </list>
        <list>
            <prt_ord>
                <![CDATA[21300]]>
            </prt_ord>
            <dept>
                <![CDATA[A201160216]]>
            </dept>
            <dept_code_nm>
                <![CDATA[A201160216-경제학부]]>
            </dept_code_nm>
            <dept_nm>
                <![CDATA[경제학부]]>
            </dept_nm>
            <up_nm>
                <![CDATA[정경대학]]>
            </up_nm>
            <up_dept>
                <![CDATA[A201120212]]>
            </up_dept>
            <dept_div>
                <![CDATA[210]]>
            </dept_div>
            <colg>
                <![CDATA[20112]]>
            </colg>
            <colg_nm>
                <![CDATA[정경대학]]>
            </colg_nm>
        </list>
        <list>
            <prt_ord>
                <![CDATA[21400]]>
            </prt_ord>
            <dept>
                <![CDATA[A201170217]]>
            </dept>
            <dept_code_nm>
                <![CDATA[A201170217-사회복지학과]]>
            </dept_code_nm>
            <dept_nm>
                <![CDATA[사회복지학과]]>
            </dept_nm>
            <up_nm>
                <![CDATA[정경대학]]>
            </up_nm>
            <up_dept>
                <![CDATA[A201120212]]>
            </up_dept>
            <dept_div>
                <![CDATA[210]]>
            </dept_div>
            <colg>
                <![CDATA[20112]]>
            </colg>
            <colg_nm>
                <![CDATA[정경대학]]>
            </colg_nm>
        </list>
        <list>
            <prt_ord>
                <![CDATA[21500]]>
            </prt_ord>
            <dept>
                <![CDATA[A201180218]]>
            </dept>
            <dept_code_nm>
                <![CDATA[A201180218-세무학과]]>
            </dept_code_nm>
            <dept_nm>
                <![CDATA[세무학과]]>
            </dept_nm>
            <up_nm>
                <![CDATA[정경대학]]>
            </up_nm>
            <up_dept>
                <![CDATA[A201120212]]>
            </up_dept>
            <dept_div>
                <![CDATA[210]]>
            </dept_div>
            <colg>
                <![CDATA[20112]]>
            </colg>
            <colg_nm>
                <![CDATA[정경대학]]>
            </colg_nm>
        </list>
        <list>
            <prt_ord>
                <![CDATA[22100]]>
            </prt_ord>
            <dept>
                <![CDATA[A201190219]]>
            </dept>
            <dept_code_nm>
                <![CDATA[A201190219-경영학부]]>
            </dept_code_nm>
            <dept_nm>
                <![CDATA[경영학부]]>
            </dept_nm>
            <up_nm>
                <![CDATA[경영대학]]>
            </up_nm>
            <up_dept>
                <![CDATA[A201130213]]>
            </up_dept>
            <dept_div>
                <![CDATA[210]]>
            </dept_div>
            <colg>
                <![CDATA[20113]]>
            </colg>
            <colg_nm>
                <![CDATA[경영대학]]>
            </colg_nm>
        </list>
        <list>
            <prt_ord>
                <![CDATA[23001]]>
            </prt_ord>
            <dept>
                <![CDATA[A204110511]]>
            </dept>
            <dept_code_nm>
                <![CDATA[A204110511-공과대학(학과)]]>
            </dept_code_nm>
            <dept_nm>
                <![CDATA[공과대학(학과)]]>
            </dept_nm>
            <up_nm>
                <![CDATA[공과대학]]>
            </up_nm>
            <up_dept>
                <![CDATA[A200110111]]>
            </up_dept>
            <dept_div>
                <![CDATA[210]]>
            </dept_div>
            <colg>
                <![CDATA[20011]]>
            </colg>
            <colg_nm>
                <![CDATA[공과대학]]>
            </colg_nm>
        </list>
        <list>
            <prt_ord>
                <![CDATA[23100]]>
            </prt_ord>
            <dept>
                <![CDATA[A200160116]]>
            </dept>
            <dept_code_nm>
                <![CDATA[A200160116-전자전기컴퓨터공학부]]>
            </dept_code_nm>
            <dept_nm>
                <![CDATA[전자전기컴퓨터공학부]]>
            </dept_nm>
            <up_nm>
                <![CDATA[공과대학]]>
            </up_nm>
            <up_dept>
                <![CDATA[A200110111]]>
            </up_dept>
            <dept_div>
                <![CDATA[220]]>
            </dept_div>
            <colg>
                <![CDATA[20011]]>
            </colg>
            <colg_nm>
                <![CDATA[공과대학]]>
            </colg_nm>
        </list>
        <list>
            <prt_ord>
                <![CDATA[23200]]>
            </prt_ord>
            <dept>
                <![CDATA[A200130113]]>
            </dept>
            <dept_code_nm>
                <![CDATA[A200130113-화학공학과]]>
            </dept_code_nm>
            <dept_nm>
                <![CDATA[화학공학과]]>
            </dept_nm>
            <up_nm>
                <![CDATA[공과대학]]>
            </up_nm>
            <up_dept>
                <![CDATA[A200110111]]>
            </up_dept>
            <dept_div>
                <![CDATA[210]]>
            </dept_div>
            <colg>
                <![CDATA[20011]]>
            </colg>
            <colg_nm>
                <![CDATA[공과대학]]>
            </colg_nm>
        </list>
        <list>
            <prt_ord>
                <![CDATA[23300]]>
            </prt_ord>
            <dept>
                <![CDATA[A200170117]]>
            </dept>
            <dept_code_nm>
                <![CDATA[A200170117-기계정보공학과]]>
            </dept_code_nm>
            <dept_nm>
                <![CDATA[기계정보공학과]]>
            </dept_nm>
            <up_nm>
                <![CDATA[공과대학]]>
            </up_nm>
            <up_dept>
                <![CDATA[A200110111]]>
            </up_dept>
            <dept_div>
                <![CDATA[210]]>
            </dept_div>
            <colg>
                <![CDATA[20011]]>
            </colg>
            <colg_nm>
                <![CDATA[공과대학]]>
            </colg_nm>
        </list>
        <list>
            <prt_ord>
                <![CDATA[23400]]>
            </prt_ord>
            <dept>
                <![CDATA[A200180118]]>
            </dept>
            <dept_code_nm>
                <![CDATA[A200180118-신소재공학과]]>
            </dept_code_nm>
            <dept_nm>
                <![CDATA[신소재공학과]]>
            </dept_nm>
            <up_nm>
                <![CDATA[공과대학]]>
            </up_nm>
            <up_dept>
                <![CDATA[A200110111]]>
            </up_dept>
            <dept_div>
                <![CDATA[210]]>
            </dept_div>
            <colg>
                <![CDATA[20011]]>
            </colg>
            <colg_nm>
                <![CDATA[공과대학]]>
            </colg_nm>
        </list>
        <list>
            <prt_ord>
                <![CDATA[23500]]>
            </prt_ord>
            <dept>
                <![CDATA[A200190119]]>
            </dept>
            <dept_code_nm>
                <![CDATA[A200190119-토목공학과]]>
            </dept_code_nm>
            <dept_nm>
                <![CDATA[토목공학과]]>
            </dept_nm>
            <up_nm>
                <![CDATA[공과대학]]>
            </up_nm>
            <up_dept>
                <![CDATA[A200110111]]>
            </up_dept>
            <dept_div>
                <![CDATA[210]]>
            </dept_div>
            <colg>
                <![CDATA[20011]]>
            </colg>
            <colg_nm>
                <![CDATA[공과대학]]>
            </colg_nm>
        </list>
        <list>
            <prt_ord>
                <![CDATA[23600]]>
            </prt_ord>
            <dept>
                <![CDATA[A200200120]]>
            </dept>
            <dept_code_nm>
                <![CDATA[A200200120-컴퓨터과학부]]>
            </dept_code_nm>
            <dept_nm>
                <![CDATA[컴퓨터과학부]]>
            </dept_nm>
            <up_nm>
                <![CDATA[공과대학]]>
            </up_nm>
            <up_dept>
                <![CDATA[A200110111]]>
            </up_dept>
            <dept_div>
                <![CDATA[210]]>
            </dept_div>
            <colg>
                <![CDATA[20011]]>
            </colg>
            <colg_nm>
                <![CDATA[공과대학]]>
            </colg_nm>
        </list>
        <list>
            <prt_ord>
                <![CDATA[24100]]>
            </prt_ord>
            <dept>
                <![CDATA[A200230123]]>
            </dept>
            <dept_code_nm>
                <![CDATA[A200230123-영어영문학과]]>
            </dept_code_nm>
            <dept_nm>
                <![CDATA[영어영문학과]]>
            </dept_nm>
            <up_nm>
                <![CDATA[인문대학]]>
            </up_nm>
            <up_dept>
                <![CDATA[A200220122]]>
            </up_dept>
            <dept_div>
                <![CDATA[210]]>
            </dept_div>
            <colg>
                <![CDATA[20022]]>
            </colg>
            <colg_nm>
                <![CDATA[인문대학]]>
            </colg_nm>
        </list>
        <list>
            <prt_ord>
                <![CDATA[24200]]>
            </prt_ord>
            <dept>
                <![CDATA[A200240124]]>
            </dept>
            <dept_code_nm>
                <![CDATA[A200240124-국어국문학과]]>
            </dept_code_nm>
            <dept_nm>
                <![CDATA[국어국문학과]]>
            </dept_nm>
            <up_nm>
                <![CDATA[인문대학]]>
            </up_nm>
            <up_dept>
                <![CDATA[A200220122]]>
            </up_dept>
            <dept_div>
                <![CDATA[210]]>
            </dept_div>
            <colg>
                <![CDATA[20022]]>
            </colg>
            <colg_nm>
                <![CDATA[인문대학]]>
            </colg_nm>
        </list>
        <list>
            <prt_ord>
                <![CDATA[24300]]>
            </prt_ord>
            <dept>
                <![CDATA[A200250125]]>
            </dept>
            <dept_code_nm>
                <![CDATA[A200250125-국사학과]]>
            </dept_code_nm>
            <dept_nm>
                <![CDATA[국사학과]]>
            </dept_nm>
            <up_nm>
                <![CDATA[인문대학]]>
            </up_nm>
            <up_dept>
                <![CDATA[A200220122]]>
            </up_dept>
            <dept_div>
                <![CDATA[210]]>
            </dept_div>
            <colg>
                <![CDATA[20022]]>
            </colg>
            <colg_nm>
                <![CDATA[인문대학]]>
            </colg_nm>
        </list>
        <list>
            <prt_ord>
                <![CDATA[24400]]>
            </prt_ord>
            <dept>
                <![CDATA[A200260126]]>
            </dept>
            <dept_code_nm>
                <![CDATA[A200260126-철학과]]>
            </dept_code_nm>
            <dept_nm>
                <![CDATA[철학과]]>
            </dept_nm>
            <up_nm>
                <![CDATA[인문대학]]>
            </up_nm>
            <up_dept>
                <![CDATA[A200220122]]>
            </up_dept>
            <dept_div>
                <![CDATA[210]]>
            </dept_div>
            <colg>
                <![CDATA[20022]]>
            </colg>
            <colg_nm>
                <![CDATA[인문대학]]>
            </colg_nm>
        </list>
        <list>
            <prt_ord>
                <![CDATA[24500]]>
            </prt_ord>
            <dept>
                <![CDATA[A201020202]]>
            </dept>
            <dept_code_nm>
                <![CDATA[A201020202-중국어문화학과]]>
            </dept_code_nm>
            <dept_nm>
                <![CDATA[중국어문화학과]]>
            </dept_nm>
            <up_nm>
                <![CDATA[인문대학]]>
            </up_nm>
            <up_dept>
                <![CDATA[A200220122]]>
            </up_dept>
            <dept_div>
                <![CDATA[210]]>
            </dept_div>
            <colg>
                <![CDATA[20022]]>
            </colg>
            <colg_nm>
                <![CDATA[인문대학]]>
            </colg_nm>
        </list>
        <list>
            <prt_ord>
                <![CDATA[25100]]>
            </prt_ord>
            <dept>
                <![CDATA[A200310131]]>
            </dept>
            <dept_code_nm>
                <![CDATA[A200310131-수학과]]>
            </dept_code_nm>
            <dept_nm>
                <![CDATA[수학과]]>
            </dept_nm>
            <up_nm>
                <![CDATA[자연과학대학]]>
            </up_nm>
            <up_dept>
                <![CDATA[A200280128]]>
            </up_dept>
            <dept_div>
                <![CDATA[210]]>
            </dept_div>
            <colg>
                <![CDATA[20028]]>
            </colg>
            <colg_nm>
                <![CDATA[자연과학대학]]>
            </colg_nm>
        </list>
        <list>
            <prt_ord>
                <![CDATA[25200]]>
            </prt_ord>
            <dept>
                <![CDATA[A200300130]]>
            </dept>
            <dept_code_nm>
                <![CDATA[A200300130-통계학과]]>
            </dept_code_nm>
            <dept_nm>
                <![CDATA[통계학과]]>
            </dept_nm>
            <up_nm>
                <![CDATA[자연과학대학]]>
            </up_nm>
            <up_dept>
                <![CDATA[A200280128]]>
            </up_dept>
            <dept_div>
                <![CDATA[210]]>
            </dept_div>
            <colg>
                <![CDATA[20028]]>
            </colg>
            <colg_nm>
                <![CDATA[자연과학대학]]>
            </colg_nm>
        </list>
        <list>
            <prt_ord>
                <![CDATA[25300]]>
            </prt_ord>
            <dept>
                <![CDATA[A200320132]]>
            </dept>
            <dept_code_nm>
                <![CDATA[A200320132-물리학과]]>
            </dept_code_nm>
            <dept_nm>
                <![CDATA[물리학과]]>
            </dept_nm>
            <up_nm>
                <![CDATA[자연과학대학]]>
            </up_nm>
            <up_dept>
                <![CDATA[A200280128]]>
            </up_dept>
            <dept_div>
                <![CDATA[210]]>
            </dept_div>
            <colg>
                <![CDATA[20028]]>
            </colg>
            <colg_nm>
                <![CDATA[자연과학대학]]>
            </colg_nm>
        </list>
        <list>
            <prt_ord>
                <![CDATA[25400]]>
            </prt_ord>
            <dept>
                <![CDATA[A200330133]]>
            </dept>
            <dept_code_nm>
                <![CDATA[A200330133-생명과학과]]>
            </dept_code_nm>
            <dept_nm>
                <![CDATA[생명과학과]]>
            </dept_nm>
            <up_nm>
                <![CDATA[자연과학대학]]>
            </up_nm>
            <up_dept>
                <![CDATA[A200280128]]>
            </up_dept>
            <dept_div>
                <![CDATA[210]]>
            </dept_div>
            <colg>
                <![CDATA[20028]]>
            </colg>
            <colg_nm>
                <![CDATA[자연과학대학]]>
            </colg_nm>
        </list>
        <list>
            <prt_ord>
                <![CDATA[25500]]>
            </prt_ord>
            <dept>
                <![CDATA[A200290129]]>
            </dept>
            <dept_code_nm>
                <![CDATA[A200290129-환경원예학과]]>
            </dept_code_nm>
            <dept_nm>
                <![CDATA[환경원예학과]]>
            </dept_nm>
            <up_nm>
                <![CDATA[자연과학대학]]>
            </up_nm>
            <up_dept>
                <![CDATA[A200280128]]>
            </up_dept>
            <dept_div>
                <![CDATA[210]]>
            </dept_div>
            <colg>
                <![CDATA[20028]]>
            </colg>
            <colg_nm>
                <![CDATA[자연과학대학]]>
            </colg_nm>
        </list>
        <list>
            <prt_ord>
                <![CDATA[26100]]>
            </prt_ord>
            <dept>
                <![CDATA[A200380138]]>
            </dept>
            <dept_code_nm>
                <![CDATA[A200380138-도시행정학과]]>
            </dept_code_nm>
            <dept_nm>
                <![CDATA[도시행정학과]]>
            </dept_nm>
            <up_nm>
                <![CDATA[도시과학대학]]>
            </up_nm>
            <up_dept>
                <![CDATA[A200370137]]>
            </up_dept>
            <dept_div>
                <![CDATA[210]]>
            </dept_div>
            <colg>
                <![CDATA[20037]]>
            </colg>
            <colg_nm>
                <![CDATA[도시과학대학]]>
            </colg_nm>
        </list>
        <list>
            <prt_ord>
                <![CDATA[26300]]>
            </prt_ord>
            <dept>
                <![CDATA[A200400140]]>
            </dept>
            <dept_code_nm>
                <![CDATA[A200400140-도시사회학과]]>
            </dept_code_nm>
            <dept_nm>
                <![CDATA[도시사회학과]]>
            </dept_nm>
            <up_nm>
                <![CDATA[도시과학대학]]>
            </up_nm>
            <up_dept>
                <![CDATA[A200370137]]>
            </up_dept>
            <dept_div>
                <![CDATA[210]]>
            </dept_div>
            <colg>
                <![CDATA[20037]]>
            </colg>
            <colg_nm>
                <![CDATA[도시과학대학]]>
            </colg_nm>
        </list>
        <list>
            <prt_ord>
                <![CDATA[26501]]>
            </prt_ord>
            <dept>
                <![CDATA[A200890189]]>
            </dept>
            <dept_code_nm>
                <![CDATA[A200890189-건축학전공]]>
            </dept_code_nm>
            <dept_nm>
                <![CDATA[건축학전공]]>
            </dept_nm>
            <up_nm>
                <![CDATA[건축학부]]>
            </up_nm>
            <up_dept>
                <![CDATA[A200480148]]>
            </up_dept>
            <dept_div>
                <![CDATA[221]]>
            </dept_div>
            <colg>
                <![CDATA[20037]]>
            </colg>
            <colg_nm>
                <![CDATA[도시과학대학]]>
            </colg_nm>
        </list>
        <list>
            <prt_ord>
                <![CDATA[26502]]>
            </prt_ord>
            <dept>
                <![CDATA[A200900190]]>
            </dept>
            <dept_code_nm>
                <![CDATA[A200900190-건축공학전공]]>
            </dept_code_nm>
            <dept_nm>
                <![CDATA[건축공학전공]]>
            </dept_nm>
            <up_nm>
                <![CDATA[건축학부]]>
            </up_nm>
            <up_dept>
                <![CDATA[A200480148]]>
            </up_dept>
            <dept_div>
                <![CDATA[221]]>
            </dept_div>
            <colg>
                <![CDATA[20037]]>
            </colg>
            <colg_nm>
                <![CDATA[도시과학대학]]>
            </colg_nm>
        </list>
        <list>
            <prt_ord>
                <![CDATA[26600]]>
            </prt_ord>
            <dept>
                <![CDATA[A200490149]]>
            </dept>
            <dept_code_nm>
                <![CDATA[A200490149-도시공학과]]>
            </dept_code_nm>
            <dept_nm>
                <![CDATA[도시공학과]]>
            </dept_nm>
            <up_nm>
                <![CDATA[도시과학대학]]>
            </up_nm>
            <up_dept>
                <![CDATA[A200370137]]>
            </up_dept>
            <dept_div>
                <![CDATA[210]]>
            </dept_div>
            <colg>
                <![CDATA[20037]]>
            </colg>
            <colg_nm>
                <![CDATA[도시과학대학]]>
            </colg_nm>
        </list>
        <list>
            <prt_ord>
                <![CDATA[26700]]>
            </prt_ord>
            <dept>
                <![CDATA[A200500150]]>
            </dept>
            <dept_code_nm>
                <![CDATA[A200500150-교통공학과]]>
            </dept_code_nm>
            <dept_nm>
                <![CDATA[교통공학과]]>
            </dept_nm>
            <up_nm>
                <![CDATA[도시과학대학]]>
            </up_nm>
            <up_dept>
                <![CDATA[A200370137]]>
            </up_dept>
            <dept_div>
                <![CDATA[210]]>
            </dept_div>
            <colg>
                <![CDATA[20037]]>
            </colg>
            <colg_nm>
                <![CDATA[도시과학대학]]>
            </colg_nm>
        </list>
        <list>
            <prt_ord>
                <![CDATA[26800]]>
            </prt_ord>
            <dept>
                <![CDATA[A200510151]]>
            </dept>
            <dept_code_nm>
                <![CDATA[A200510151-조경학과]]>
            </dept_code_nm>
            <dept_nm>
                <![CDATA[조경학과]]>
            </dept_nm>
            <up_nm>
                <![CDATA[도시과학대학]]>
            </up_nm>
            <up_dept>
                <![CDATA[A200370137]]>
            </up_dept>
            <dept_div>
                <![CDATA[210]]>
            </dept_div>
            <colg>
                <![CDATA[20037]]>
            </colg>
            <colg_nm>
                <![CDATA[도시과학대학]]>
            </colg_nm>
        </list>
        <list>
            <prt_ord>
                <![CDATA[26900]]>
            </prt_ord>
            <dept>
                <![CDATA[A200450145]]>
            </dept>
            <dept_code_nm>
                <![CDATA[A200450145-환경공학부]]>
            </dept_code_nm>
            <dept_nm>
                <![CDATA[환경공학부]]>
            </dept_nm>
            <up_nm>
                <![CDATA[도시과학대학]]>
            </up_nm>
            <up_dept>
                <![CDATA[A200370137]]>
            </up_dept>
            <dept_div>
                <![CDATA[220]]>
            </dept_div>
            <colg>
                <![CDATA[20037]]>
            </colg>
            <colg_nm>
                <![CDATA[도시과학대학]]>
            </colg_nm>
        </list>
        <list>
            <prt_ord>
                <![CDATA[26951]]>
            </prt_ord>
            <dept>
                <![CDATA[A201000200]]>
            </dept>
            <dept_code_nm>
                <![CDATA[A201000200-공간정보공학과]]>
            </dept_code_nm>
            <dept_nm>
                <![CDATA[공간정보공학과]]>
            </dept_nm>
            <up_nm>
                <![CDATA[도시과학대학]]>
            </up_nm>
            <up_dept>
                <![CDATA[A200370137]]>
            </up_dept>
            <dept_div>
                <![CDATA[210]]>
            </dept_div>
            <colg>
                <![CDATA[20037]]>
            </colg>
            <colg_nm>
                <![CDATA[도시과학대학]]>
            </colg_nm>
        </list>
        <list>
            <prt_ord>
                <![CDATA[26998]]>
            </prt_ord>
            <dept>
                <![CDATA[A201010201]]>
            </dept>
            <dept_code_nm>
                <![CDATA[A201010201-소방방재학과]]>
            </dept_code_nm>
            <dept_nm>
                <![CDATA[소방방재학과]]>
            </dept_nm>
            <up_nm>
                <![CDATA[도시과학대학]]>
            </up_nm>
            <up_dept>
                <![CDATA[A200370137]]>
            </up_dept>
            <dept_div>
                <![CDATA[210]]>
            </dept_div>
            <colg>
                <![CDATA[20037]]>
            </colg>
            <colg_nm>
                <![CDATA[도시과학대학]]>
            </colg_nm>
        </list>
        <list>
            <prt_ord>
                <![CDATA[27150]]>
            </prt_ord>
            <dept>
                <![CDATA[A200810181]]>
            </dept>
            <dept_code_nm>
                <![CDATA[A200810181-공업디자인전공]]>
            </dept_code_nm>
            <dept_nm>
                <![CDATA[공업디자인전공]]>
            </dept_nm>
            <up_nm>
                <![CDATA[산업디자인학과]]>
            </up_nm>
            <up_dept>
                <![CDATA[A200600160]]>
            </up_dept>
            <dept_div>
                <![CDATA[221]]>
            </dept_div>
            <colg>
                <![CDATA[20059]]>
            </colg>
            <colg_nm>
                <![CDATA[예술체육대학]]>
            </colg_nm>
        </list>
        <list>
            <prt_ord>
                <![CDATA[27160]]>
            </prt_ord>
            <dept>
                <![CDATA[A200820182]]>
            </dept>
            <dept_code_nm>
                <![CDATA[A200820182-시각디자인전공]]>
            </dept_code_nm>
            <dept_nm>
                <![CDATA[시각디자인전공]]>
            </dept_nm>
            <up_nm>
                <![CDATA[산업디자인학과]]>
            </up_nm>
            <up_dept>
                <![CDATA[A200600160]]>
            </up_dept>
            <dept_div>
                <![CDATA[221]]>
            </dept_div>
            <colg>
                <![CDATA[20059]]>
            </colg>
            <colg_nm>
                <![CDATA[예술체육대학]]>
            </colg_nm>
        </list>
        <list>
            <prt_ord>
                <![CDATA[27200]]>
            </prt_ord>
            <dept>
                <![CDATA[A200610161]]>
            </dept>
            <dept_code_nm>
                <![CDATA[A200610161-환경조각학과]]>
            </dept_code_nm>
            <dept_nm>
                <![CDATA[환경조각학과]]>
            </dept_nm>
            <up_nm>
                <![CDATA[예술체육대학]]>
            </up_nm>
            <up_dept>
                <![CDATA[A200590159]]>
            </up_dept>
            <dept_div>
                <![CDATA[210]]>
            </dept_div>
            <colg>
                <![CDATA[20059]]>
            </colg>
            <colg_nm>
                <![CDATA[예술체육대학]]>
            </colg_nm>
        </list>
        <list>
            <prt_ord>
                <![CDATA[27300]]>
            </prt_ord>
            <dept>
                <![CDATA[A200620162]]>
            </dept>
            <dept_code_nm>
                <![CDATA[A200620162-음악학과]]>
            </dept_code_nm>
            <dept_nm>
                <![CDATA[음악학과]]>
            </dept_nm>
            <up_nm>
                <![CDATA[예술체육대학]]>
            </up_nm>
            <up_dept>
                <![CDATA[A200590159]]>
            </up_dept>
            <dept_div>
                <![CDATA[210]]>
            </dept_div>
            <colg>
                <![CDATA[20059]]>
            </colg>
            <colg_nm>
                <![CDATA[예술체육대학]]>
            </colg_nm>
        </list>
        <list>
            <prt_ord>
                <![CDATA[27400]]>
            </prt_ord>
            <dept>
                <![CDATA[A200540154]]>
            </dept>
            <dept_code_nm>
                <![CDATA[A200540154-스포츠과학과]]>
            </dept_code_nm>
            <dept_nm>
                <![CDATA[스포츠과학과]]>
            </dept_nm>
            <up_nm>
                <![CDATA[예술체육대학]]>
            </up_nm>
            <up_dept>
                <![CDATA[A200590159]]>
            </up_dept>
            <dept_div>
                <![CDATA[210]]>
            </dept_div>
            <colg>
                <![CDATA[20059]]>
            </colg>
            <colg_nm>
                <![CDATA[예술체육대학]]>
            </colg_nm>
        </list>
        <list>
            <prt_ord>
                <![CDATA[28210]]>
            </prt_ord>
            <dept>
                <![CDATA[A201110211]]>
            </dept>
            <dept_code_nm>
                <![CDATA[A201110211-국제교육원(학사-과)]]>
            </dept_code_nm>
            <dept_nm>
                <![CDATA[국제교육원(학사-과)]]>
            </dept_nm>
            <up_nm>
                <![CDATA[국제교육원(학사)]]>
            </up_nm>